<?php
//=====================管理员后台==================
$mem['product'][1][0]=array(
	'产品管理',
	array(
		'product.php,1,product,产品列表',
		'product_launch.php,1,product,产品发布',
		'product_consult.php,1,product,产品咨询',
		'product_comment.php,1,product,产品评价',
	),
);
$mem['product'][1][1]=array(
	'产品配置',
	array(
		'module_config.php,1,product,模块设置',
		'product_cat.php,1,product,分类管理',
		'product_tag.php,1,product,标签管理',
		'product_service.php,1,product,服务管理',
		'brand.php,1,brand,品牌管理',
		'property.php,1,product,属性管理',
		'spec.php,1,product,规格管理',
	),	
);
$mem['business'][1][0]=array(
	'订单管理',
	array(
		'order.php,1,product,订单列表',
		'order_payment.php,1,product,付款单',
		'order_shipping.php,1,product,发货单',
	)
);

?>